// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-Re1DVMcptfTxG1Zi_7h0-pBk-LRGoE',
    appId: '1:1044997610309:web:f055f4e0d14fe93cee3c2c',
    messagingSenderId: '1044997610309',
    projectId: 'grad-ceed6',
    authDomain: 'grad-ceed6.firebaseapp.com',
    storageBucket: 'grad-ceed6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNiNHFg4xeM3HUq4LyviZHS8O6O6oeQs',
    appId: '1:1044997610309:android:d570d7a54d3853ccee3c2c',
    messagingSenderId: '1044997610309',
    projectId: 'grad-ceed6',
    storageBucket: 'grad-ceed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRfdJ97DNb5bvBzrpNDwdCOxaj-3MyGY',
    appId: '1:1044997610309:ios:db2433da4fe5a94eee3c2c',
    messagingSenderId: '1044997610309',
    projectId: 'grad-ceed6',
    storageBucket: 'grad-ceed6.appspot.com',
    iosClientId: '1044997610309-dq02j6prv61juijon93ke4911rmhql7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradproject',
  );
}
